config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root "events#index"

  # resources :events
  # resources :rsvps, only: [:create, :destroy]
  
  resources :events do
    resources :rsvps
  end

  # resources :users do
  #   resources :rsvps, only: [:index, :new, :create]
  # end
  # resources :rsvps, only: :destroy
  
  # post '/events/:id/rsvp', to: 'events#rsvp'
  # post '/events/:id/rsvp', to: 'events#rsvp', as: 'attend_event'
  
  
  # get 'events/index', to: "events#index"
  # get 'events/create'
  # get 'events/new'
  # get 'events/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  date        :date
#  description :string
#  is_private  :boolean          default(FALSE), not null
#  location    :string
#  start_time  :time
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  creator_id  :integer          not null
#
# Indexes
#
#  index_events_on_creator_id  (creator_id)
#
# Foreign Keys
#
#  creator_id  (creator_id => users.id)
#
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :rsvps, foreign_key: :attended_event_id, dependent: :delete_all
  has_many :attendees, through: :rsvps

  scope :past, -> { where("DATE(date) < ?", Date.today)}
  scope :future, -> { where("DATE(date) >= ?", Date.today)}
  scope :is_public, -> { where(is_private: false)}
  
end

app/models/rsvp.rb
# == Schema Information
#
# Table name: rsvps
#
#  id                :integer          not null, primary key
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  attended_event_id :integer          not null
#  attendee_id       :integer          not null
#
# Indexes
#
#  index_rsvps_on_attended_event_id  (attended_event_id)
#  index_rsvps_on_attendee_id        (attendee_id)
#
# Foreign Keys
#
#  attended_event_id  (attended_event_id => events.id)
#  attendee_id        (attendee_id => users.id)
#
class Rsvp < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :created_events, class_name: 'Event', foreign_key: "creator_id", inverse_of: 'creator'

  has_many :rsvps, foreign_key: :attendee_id, dependent: :delete_all
  # , class_name: 'User'
  has_many :attended_events, through: :rsvps
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :get_usernames, only: %i[ edit update show destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
 

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.new(event_params)
    if @event.save
      flash[:success] = "Great! Your event has been created!"
      redirect_to @event
    else
      flash.now[:error] = @event.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def index
    # scope to see all events
    # @events = Event.all.order(date: :asc)
    # scope to only view non-private events
    @events = Event.is_public.order(date: :asc)
    # scope to see own events only
    # @events = current_user.events
    @attended_events = current_user.attended_events.order(date: :asc)
    
  end

  def show
    @event = Event.find(params[:id])
    get_usernames
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "event was successfully destroyed."
    redirect_to root_path, status: :see_other
  end

  def edit
    # @event = Event.find(params[:id])
  end

  def update
      if @event.update(event_params)
        flash[:success] = "event was successfully updated."
        redirect_to event_url(@event)
      else
        flash.now[:error] = @event.errors.full_messages.to_sentence
        render :edit, status: :unprocessable_entity
      end
  end

  private
  def event_params
    params.require(:event).permit(:date, :location, :start_time, :title, :description, :creator_id, :is_private, :id)
  end
  def set_event
    # users can see all events
    @event = Event.find(params[:id])
    # users can only see their own events
    # @event = current_user.events.find(params[:id])
  end
  def get_usernames
    people = User.find(@event.attendee_ids)
    @usernames = people.pluck(:username)
  end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @rsvp = Rsvp.new(attendee_id: current_user.id, attended_event_id: params[:event_id])
    # @rsvp = Rsvp.new(rsvp_params)
    if !@rsvp.save
      flash[:notice] = @rsvp.errors.full_messages.to_sentence
    else
      flash[:success] = "You're registered to attend!"
    end
    # redirect_to event_url
    redirect_back(fallback_location: events_url)
  end

  def destroy
    @rsvp = Rsvp.find_by(attendee_id: current_user.id, attended_event_id: params[:event_id])
    # @rsvp = current_user.rsvps.find(params[:event_id])
    # rsvp = @rsvp.attended_event
    
    @rsvp.destroy
    redirect_to event_url
    # redirect_back(fallback_location: events_url)
  end

  private


  def rsvp_params
    params.require(:rsvp).permit(:attendee_id, :attended_event_id, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attended_events_helper.rb
module AttendedEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<td><%= "#{event.date}" %></td>
<td><%= "#{event.location}" %></td>
<td><%= "#{event.creator.username}" %></td>
<td><%= "#{event.rsvps.count}" %></td>
<td><%= link_to event.title, event %></td>
<td><%= "#{event.description}" %></td>

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.date_select :date %>
    <% event.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :start_time %><br>
    <%= form.text_field :start_time %>
    <% event.errors.full_messages_for(:start_time).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
    <% event.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% event.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div> 

    <%= form.label :is_private %> <br>
    <%= form.check_box :is_private %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<h1>Editing Event</h1>


<%= render "form", event: @event %>


<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

<%= link_to "New Event", new_event_path %>
<h2>All events</h2>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th>Host</th>
      <th>Attendees</th>
      <th>Title</th>
      <th>Details</th>
    </tr>
  </thead>
  <tbody id = "events">
    <% @events.each do |event| %>
      <tr><%= render event %></tr>
    <% end %>
  </tbody>
</table>
<hr>
<h3>Events you're attending:</h3>
  <% @attended_events.future.each do |event| %>
    <li><%= render event %></li>
  <% end %>
  <hr>
  <h3>Events you're hosting:</h3>
  <% current_user.created_events.future.each do |event| %>
    <li><%= render event %></li>
  <% end %>
<hr>
<h4>Your Past Events: </h4>
  <% @attended_events.past.each do |event| %>
    <li><%= render event %></li>
  <% end %>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

<%= render "form", event: @event %>


<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>Event</h1>
<p><%= p params %></p>
<p id='notice' style="color: green"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <h1><%= @event.title %></h1>
<div>
  <%= render '/rsvps/button', event: @event %>
</div>
<div>
  <p>Date: <%= @event.date %></p>
  <p>Location :<%= @event.location %></p>
  <p>Created by: <%= @event.creator.username %></p>
  <p>Event Description:</p>
  <p><%= @event.description %></p>
  <p>Attendees</p>
  <p>Total: <%= @event.rsvps.count %> people</p>
  <p>Names: <%= @usernames %></p>
  <p>Private: <%= @event.is_private %></p>
</div>


<div>
  <%= link_to "Back to events", events_path %>
  <% if Event.future.include?(@event) %>
    <%= link_to "Edit this event", edit_event_path(@event) %> |
    <%= button_to "Destroy this event", @event, method: :delete %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Priventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Hi #{current_user.username}!", edit_user_registration_path %></li>
        <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>

      <% end %>
    </ul>
    
    <%= yield %>
  </body>
</html>

app/views/rsvps/_button.html.erb
<%= event.attendees.count %> Attendees
<br>
<% if Event.past.include?(event) %>
    <p>Registration closed - event already happened</p>
<% else %>
    <% if event.attendees.include?(current_user) %>
      <p>You signed up!</p>
      <%= button_to "Withdraw", event_rsvp_path(event), method: :delete %> 
    <% else %>
      <%= button_to "Attend", event_rsvps_path(event), params: { rsvp:{ attendee_id: current_user.id, attended_event_id: event.id} }, method: :post %>
    <% end %>
<% end %>